[package]
name = "embedded_wav"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.14.0"

[dependencies.nom]
version = "7.1.1"
default-features = false